### ISSUE TITLE
Enhancement: Support data attributes (for lazy loading)

### ISSUE THREAD

**Issue by pepebe** [modxcms/imageSlim#4]
Lazyloading images can be done in a multitude of ways.

One common technique is to add the image path to a data-attribute and use a generic 1px transparent gif as source for all images. Utilizing js images are loaded at a later point.

Example:

```
<img data-original="http://artmetropol.tv/id/00000/0000/100/10/1/vorschau_111.jpg" alt="" class="lazy dfs" src="lazy.gif">
```

A nice lazy loading jquery plugin: http://www.appelsiini.net/projects/lazyload

It would be great, to tell imageSlim to use other attributes instead of the default src one.

Example:

```
[[imageSlim? &input=`[[*content]]` &source=`data-original`  &phpthumbof=`fltr[]=gray`]]
```

&source could default to "src" but allow any other attribute as well.

Regards,

pepebe

**Comment by pepebe** [comment]
I have fiddled around with imageSlim, (see gist: https://gist.github.com/pepebe/6087030) but there seems to be somehing missing to make it work.

Update: It works. The Problem seems to be parsing related. 

changes:
Line 75: $imgSrc Parameter added.

```
$imgSrc = isset($imgSrc) ? $imgSrc : "src";
```

Line 92: Changed "src" to $imgSrc 

```
$src = $node->getAttribute($imgSrc);
```

Line 276

```
$node->setAttribute( $imgSrc , $modx->runSnippet('phpthumbof', $image) );  // do the business and set the src
```

Any idea what I'm missing?

**Comment by pepebe** [comment]
Ok, the problem might be related to parsing order. I used the modified version on a simple template and it worked with data-attribute as image source. A more complex one failed, so I suppose the problem is not really related to the snippet. Is this worth a pull request?

**Comment by oo12** [comment]
Ok, I'll add this and create a new version in the next few days.  Maybe somebody else will find it useful too.
Changing those 3 lines gets most of the way there.  It's a simple change so I don't need a pull request, but thanks for the offer!

**Comment by oo12** [comment]
Added in v1.1
