### ISSUE TITLE
Improve handling in subdirectories 

### ISSUE THREAD

**Issue by Mark-H** [modxcms/imageSlim#5]
When the MODX install is in a subdirectory, but images are inserted with that base url prepended, ImageSlim prepends the base path again causing issues with the image replacement. 

Changing line 141 to this:

```
    $file = str_replace(MODX_BASE_PATH.ltrim(MODX_BASE_URL, '/'), MODX_BASE_PATH, $file);
```

sorts that problem and has no negative side effects that I know off.

**Comment by oo12** [comment]
Thanks for reporting this!  I'm not sure about the line number, but I like your fix.  In fact I'm going to use it elsewhere as well, since it's simpler than how I was going about it and works quite well.

Fixed in v1.1.1-pl.
