### ISSUE TITLE
used as a output modifier breaks textarea tag

### ISSUE THREAD

**Issue by CAD-Teamet** [modxcms/imageSlim#6]
When used as a output modifier in MODX Revolution 2.2.7-pl and the content contains a textarea (with styles) it breaks the tag syntax:

ex. [[_content:imageSlim]]
[[_content]] contains a textarea tag. Imageslim removes the end tag for textarea and adds />.

**Comment by oo12** [comment]
Hi,

See if [this version](https://raw.github.com/oo12/imageSlim/dev/core/components/imageslim/elements/snippets/imageslim.snippet.php) fixes it. Edit the imageSlim snippet in the manager and copy and paste this new version in, replacing all the old text.

**Comment by CAD-Teamet** [comment]
Yes! Problem solved! Great!

**Comment by oo12** [comment]
Ah, good! I'll add a new version to the MODX extras repo in the next few days with this fix, plus another couple little improvements.

**Comment by oo12** [comment]
Fixed in v1.1.2-pl.
